name: NHM_PRMS_Benchmarking_Widgets

dependencies:
  - python=3.7.1
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-learn
  - ipywidgets
  - joblib
  - tqdm
  - numcodecs
  - zarr
  - xarray
  - termcolor
  - mpl_chord_diagram